### ISSUE TITLE
checkArgumentsString - uppercase values

### ISSUE THREAD

**Issue by thomas2411** [Adeey/graphql-php#1]
Hello,
great work with the library, thank you.

I would like to ask a question regarding TypeBuilder

https://github.com/Adeey/graphql-php/blob/cfc28c287311987f065f9efce86fa317d1cdacb7/src/Core/TypeBuilder.php#L64

What is the purpose of this check? For instance if a give an argument like car_model with a value of BWM, then this code will add this value to the query without double quotes which then, when added to the Request with Content-Type: application/json header invokes error as you cannot send string (BMW) with json without double quotes.

**Comment by Adeey** [comment]
Hi @thomas2411, thanks for feedback, in the latest release(1.0.45) that was fixed. In case you want use ENUM value in your argument you can use it by class "Enum": 
 ```
 use MaxGraphQL\FieldTypes\Enum; 

$arguments = [
    'input' => [
        'car_model_enum' => new Enum('BMW'), // car_model_enum: BMW
        'car_model_string' => 'BMW' // car_model_string: "BMW"
    ]
];
```
